### ISSUE TITLE
Failure to load on Safari 8.0.7 with ghostery

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#515] opened 2015-07-22 23:45 UTC
From http://www.astrobetter.com/blog/2015/07/20/updates-on-ads-interfaces-and-the-announcement-of-bumblebee/#comment-2287694

I’m using Safari 8.0.7 on a Mac.
When the page starts loading, it looks as if you’re pulling in a module called “google-analytics” using require.js. Ghostery is blocking it loading. In the web inspector, I can see it polling every 50 ms for 10 seconds to check if it has loaded. After that, it simple announces a load timeout and gives up. See the screenshot at http://urchin.earth.li/~jds/Screen%20Shot%202015-07-22%20at%2019.16.45.png. I don’t speak Javascript, but from the looks of it I’m guessing that there’s nothing which is set up to handle the exception thrown in defaultOnError.

If I tell Ghostery not to block Google Analytics, this loading page is replaces after a couple of seconds with Bumblebee.

**Comment by jdswinbank** [comment] 2015-07-23 02:16
<img width="1016" alt="screen shot 2015-07-22 at 19 16 45" src="https://cloud.githubusercontent.com/assets/460854/8841681/0a90fe08-30bf-11e5-9ba6-3c6a002c5c89.png">
Attaching the screenshot here for reference -- the link in the issue description isn't guaranteed to stay active in the long term.

(Also, appropriately shame-faced about the multiple typos in the issue description!)

**Comment by romanchyla** [comment] 2015-07-23 02:28
Thanks John, this is really helping us. I tried to reproduce it before on IE/Chrome/Firefox - Win/Linux - but it was working....

I've just pushed a fix - I' deploy it on our testing environment. If you have time, pls let us know if the bugfix worker (I'll post here the link once deployed)

**Comment by romanchyla** [comment] 2015-07-23 03:13
the bugfix can be tested here: http://hourly.adslabs.org/

**Comment by jdswinbank** [comment] 2015-07-23 12:08
Thanks for looking into this so quickly. Unfortunately, it doesn't look as if this fix has done the trick. When I visit http://hourly.adslabs.org/ the observed behaviour is exactly the same as at https://ui.adsabs.harvard.edu/. The only difference is that the message which appears in the console has changed; it now reads:
```
[Warning] google-analytics could not be loaded (Ghostery trickery?)  (analytics.js, line 1)
Error
contextName: "_"
message: "Load timeout for modules: google-analytics↵http://requirejs.org/docs/errors.html#timeout"
requireModules: Array[1]
requireType: "timeout"
stack: "makeError@http://hourly.adslabs.org/libs/requirejs/require.js:166:26↵checkLoaded@http://hourly.adslabs.org/libs/requirejs/require.js:692:32↵http://hourly.adslabs.org/libs/requirejs/require.js:713:36"
__proto__: Error
```

**Comment by romanchyla** [comment] 2015-07-23 15:48
wow, thanks for trying - the good news is that message comes from our error handler, so we are detecting the situation; the not so good news is that the error still propagates up

i'll have to get hold of some mac and try with safari

**Comment by romanchyla** [comment] 2015-07-23 23:55
Hi John, ghostery is not playing well and even crashes safari - really not well behaving - and because it is playing dirty, I had to make a workaround

but i think now i got it, tested with safari on yosemite os (via saucelabs) and it loads. Please try if you can.

**Comment by romanchyla** [comment] 2015-07-23 23:55
on hourly.adslabs.org

**Comment by jdswinbank** [comment] 2015-07-24 11:14
Great! That seems to be working. Thanks. Bumblebee seems pretty slick so far; I'm looking forward to exploring further.

**Closed** 2015-07-24 18:11 UTC
Labels: bug
