### ISSUE TITLE
Date parsing error

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#775] opened 2016-01-28 21:40 UTC
This url: https://ui.adsabs.harvard.edu/#search/q=author%3A%22de+Sitter%2CW%22&sort=date+asc

Generates an uncaught javascript error:
```
Error: Error parsing input: 1901-00-00
    at r.formatDate (bumblebee_app.g3e0073b.js:1)
    at bumblebee_app.g3e0073b.js:1
    at Function.mr (bumblebee_app.g3e0073b.js:1)
    at t.extend.processDocs (bumblebee_app.g3e0073b.js:1)
    at s.processDocs (bumblebee_app.g3e0073b.js:1)
    at i.extend.processResponse (bumblebee_app.g3e0073b.js:1)
    at i (bumblebee_app.g3e0073b.js:1)
    at n.extend.triggerEvents (bumblebee_app.g3e0073b.js:1)
    at n.extend.triggerHandleErrors (bumblebee_app.g3e0073b.js:1)
    at n.extend.publish (bumblebee_app.g3e0073b.js:1)
```

**Comment by aholachek** [comment] 2016-02-11 19:59
hi @aaccomazzi I can't reproduce this, it might have been fixed by the other edit i made to the date parsing a few weeks ago

**Closed** 2016-02-19 22:01 UTC
Labels: bug
