### ISSUE TITLE
Weird search results 

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1188] opened 2017-06-20 00:36 UTC
Today I ran the following query on the production system `author:"^accomazzi, a" bibstem:ASPC" which should return 15 records, but instead 24 were returned, including many duplicates:

![image](https://user-images.githubusercontent.com/910261/27311338-406df18a-552e-11e7-9a21-0204450ca133.png)

I checked SOLR and the query returned just 14 records, no duplicates, so I can't figure out what may have gone wrong?

**Comment by ehenneken** [comment] 2017-06-20 10:40
The query returned expected results, just now, so it's probably not a Bumblebee issue

**Comment by thostetler** [comment] 2017-06-21 15:52
Closing for now, as I can't reproduce.  Feel free to re-open if it's something on the Bumblebee side.

**Closed by thostetler** 2017-06-21 15:52 UTC
