### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1128] opened 2016-12-15 23:25 UTC
Strange error from BBB today:
- Mac OS X, Chrome  54.0.2840.98 (64-bit)
- bumblebee_app.g9b3006a.js
- prior search was "accomazzi" (unfielded)
- current search was "year:2016 property:refereed database:astronomy"

Starting BBB in a new incognito window shows no problem, so something must be messed up in the current app.

![image](https://cloud.githubusercontent.com/assets/910261/21245961/ab61e762-c2f3-11e6-8c1e-c8c218014779.png)

**Comment by thostetler** [comment] 2018-02-21 18:02
Unable to reproduce, closing for now.

**Closed by thostetler** 2018-02-21 18:02 UTC
