### ISSUE TITLE
Feedback form generates an error when submitted

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#1166] opened 2017-05-17 23:51 UTC
![image](https://cloud.githubusercontent.com/assets/910261/26180883/40a41e94-3b3a-11e7-99e7-5bd5cb16918b.png)

**Comment by thostetler** [comment] 2017-05-18 13:04
Looks like a 404 getting to `https://api.adsabs.harvard.edu/v1/feedback/slack`
![image](https://cloud.githubusercontent.com/assets/6970899/26203397/00751de0-3ba9-11e7-9f00-4f25a4ef941c.png)

**Comment by ehenneken** [comment] 2017-05-18 13:08
I wonder if this is related to the disabled webhook on Slack

**Comment by thostetler** [comment] 2017-05-18 15:34
I believe the issue is resolved with the re-enabling of the Slack webhook.

**Closed by thostetler** 2017-05-18 15:34 UTC
Labels: bug, priority
